### ISSUE TITLE
Deprecate substories written in the same class.

### ISSUE THREAD

**Issue by proofit404** [dry-python/stories#388]
We have two variants to write substories:
```python
# 1. use stories from the same class
class Action:
    @story
    def do(I):
        I.step1
        I.sub
        I.step4

    @story
    def sub(I):
        I.step2
        I.step3

# 2. use composition
class Action:
    @story
    def do(I):
        I.step1
        I.sub
        I.step4

    def __init__(self, sub):
        self.sub = sub

class SubAction:
    @story
    def sub(I):
        I.step2
        I.step3

Action(SubAction().sub).do
```
These two approaches are handled differently in the code.
1. Stories written in the same class are treated as one big story with some nesting.
2. Stories written in different classes are treated as properly nested separated stories.

This design makes certain things harder.

1. Tests related to the special same class took 1/3 of the complete test suite.
2. In the #49 implementation of contract conflict detection is overly complicated.
3. In the #308 usage of the proposed API is impossible with stories written in the same class.
4. Many special cases in the representation and history of the stories written in the same class.
5. It is necessary to maintain `contract_in` and `failure_in` API.

If we took into consideration that the initial purpose of such kinds of things was grouping, it becomes clear that things took out of control. For example, if we want to have a step called `validate` in the parent story and break it into 10 steps with `validate_` prefix in the child story.

**The code with stories written in the same class will continue to work**, but...
* it's required to set different contracts for each story manually
* it's required to set different failure protocols for each story manually

**TODO**:
- [ ] remove it from the docs
- [ ] remove it from the tests
- [ ] remove all corner cases
  * drop beginning of story same object attribute
  * drop type check from class mounted story representation
  * drop **contract_in** shortcut
  * drop **failure_in** shortcut
  * force stories to have different protocols and contracts
